<?php
/**
* @file
* Block Module for displaying a Kmaps Navigator
*/

function kmaps_facets_init() {
	// error_log("loading json2: " . print_r(libraries_load('json2'),true));
	libraries_load('json2');
  // Need to add debugging (the returned object from libraries_load is the only error logging you ever get)

  //error_log("loading fancytree: " . print_r(libraries_load('fancytree','source'),true));
	libraries_load('fancytree','source');
  //error_log("loading ajaxsolr: " . print_r(libraries_load('ajaxsolr'), true));
  libraries_load('ajaxsolr');
  drupal_add_js(drupal_get_path('module', 'kmaps_facets') . "/js/kmaps_facets.js",array(
      'group' => JS_THEME,
  ));
  // drupal_add_js("https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js",array('type' => 'external'));
  // drupal_add_css("https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css",array('type' => 'external'));
  // drupal_add_css("https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css",array('type' => 'external'));

  //Add Ajax library
  drupal_add_library('system', 'drupal.ajax');
}

function kmaps_facets_help($path, $arg) {
    switch ($path) {
        case "admin/help#kmaps_facets":
            return '<p>' . t("Kmaps Search and Navigation:  So Helpful!") . '</p>';
            break;
    }
}

function kmaps_facets_menu() {

  $items = array();

  $items['admin/config/user-interface/kmaps_facets'] = array(
    'title' => 'Kmaps Facets Settings',
    'description' => 'Configure Kmaps Facets Module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kmaps_facets_settings'),
    'access arguments' => array('administer site configuration'),
   );

  return $items;
}

/**
 * Module Admin form to set number of kmap navigator (facet) blocks for site
 * Get variable by $km_block_ct = variable_get("kmaps_facets_block_count", 2);
 */
function kmaps_facets_settings(array $form, array &$form_state) {
  $form = array();

  $form['kmaps_facets_block_count'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of Kmap Facet Blocks'),
    '#default_value' => variable_get('kmaps_facets_block_count', 2),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t("The number of Kmap facet blocks to have on this site"),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Validate module settings, block number must be an integer and >= 1
 */
function kmaps_facets_settings_validate($form, &$form_state) {
	$blockct = $form_state['values']['kmaps_facets_block_count'];
  if (!is_numeric($blockct)) {
    form_set_error('kmaps_facets_block_count', t('You must enter an integer for the number of Kmap facet blocks.'));
  }
  elseif ($blockct <= 0) {
    form_set_error('kmaps_facets_block_count', t('Maximum number of blocks must be at least 1.'));
  }
}

/**
 * Implements hook_block_info().
 */
function kmaps_facets_block_info() {
	$blocks = array();
  for ($i = 1; $i <= variable_get("kmaps_facets_block_count", 2); $i++) {
    $blocks[$i]['info'] = variable_get('kmaps_facets_block_name_' . $i, 'Kmaps Facets ' . $i) . ' (Kmaps Facets)';
    // We have too many things changing per user, per page to cache.
    $blocks[$i]['cache'] = DRUPAL_NO_CACHE;
  }
  return $blocks;
}

/**
 *  Implements hook_block_configure($delta)
 *  Creates configure form for each kmap nav block
 */

function kmaps_facets_block_configure($delta = 1) {
   $form['kmaps_facets_block_name_' . $delta] = array(
    '#type' => 'textfield',
    '#title' => t('Block name'),
    '#default_value' => variable_get('kmaps_facets_block_name_' . $delta, 'Kmaps Facet Block ' . $delta),
  );
  $form['kmaps_facets_block_type_' . $delta] = array(
    '#type' => 'select',
    '#title' => t('Kmap Tree Type'),
    '#description' => t('Type of Kmap Navigator Tree to Show in Block'),
    '#default_value' => variable_get('kmaps_facets_block_type_' . $delta, 'places'),
    '#options' => drupal_map_assoc(array('places', 'subjects')),
  );
  return $form;
}


/**
 * Implements hook_block_save().
 */
function kmaps_facets_block_save($delta, $edit) {
  variable_set('kmaps_facets_block_name_' . $delta, $edit['kmaps_facets_block_name_' . $delta]);
  variable_set('kmaps_facets_block_type_' . $delta, $edit['kmaps_facets_block_type_' . $delta]);
}


/**
 * Implements hook_block_view().
 *
 * Prepares the contents of the block.
 */
function kmaps_facets_block_view($delta = 1) {
	  // Set the block type in Drupal settings
		$km_type = variable_get('kmaps_facets_block_type_' . $delta, 'places');
		drupal_add_js(array('kmaps_facets' => array("block_" . $delta . "_type" => $km_type)), 'setting');
    
		$block = _kmaps_facets_block($delta);
		return $block;
}

/**
 * Helper function to call theme
 */
function _kmaps_facets_block($delta) {
    // error_log("_kmaps_facets_block helper function...");
    // Send delta and block type to template to store in data- attributes. Duplicates Drupal.settings in block_view which we may not need
    $km_type = variable_get('kmaps_facets_block_type_' . $delta, 'places');
		$block = array(
        'subject' => '',
        'content' => theme('kmaps_facets_block', array(
            'delta' => $delta, 'kmtype' => $km_type, 'forums' => 'f', 'topics' => 't', 'parents' => 'p'
        )),
    );
//    error_log("returning: " . print_r($block,true));
    return $block;
}

/**
 * Implements hook_theme()
 *
 */
function kmaps_facets_theme() {
    $module_path = drupal_get_path('module', 'kmaps_facets');
    $base = array(
        'path' => "{$module_path}/templates",
    );
    $ret = array(
        'kmaps_facets_block' => $base + array(
                // I could define here anything I want
                // It would be called from inside the subpath theme in the module path
                // as file abc.tpl.php
                'template' => 'kmaps_facets_block',
                // To override I need file
                // 'block--<MODULE_NAME>--<DELTA>.tpl.php'
                // somewhere in my theme's folder
                // (with '-' for '_' in <MODULE_NAME> and <DELTA>)
                // <DELTA> comes from array keys in hook_block_info
                // in this case
                // block--my-module--my-module-block1.tpl.php

                'variables' => array(
                    'delta' => NULL, 'kmtype' => NULL, 'forums' => NULL, 'topics' => NULL, 'parents' => NULL
                ),
                '#attached' => array(
                    'libraries_load' => array(
                        array(
                            'fancytree'
                        ),
                        array(
                            'ajaxsolr'
                        )
                    ),
                    'library' => array(
                        'system', 'drupal.ajax'
                    ),
                )
            )
    );

    // error_log("kmaps_facets_theme returning: " . print_r($ret,true));

    return $ret;

}


